FRAMERATE = 24

UPDATE_EVERY_SECONDS = 300

USER = "admin"
PASSWORD = "maxi7500"

OBSERVER_SHIFT_HOUR = 19
NIGHT_OBSERVER_SHIFT_HOUR = 6

MOVEMENT_SENSITIVITY = 0.83

DETECTION_BATCH_SIZE = 102

YOLO_V3_TINY_WEIGHTS = "./YOLO v4/tiny/yolov4.weights"
YOLO_V3_TINY_CONFIGS = "./YOLO v4/tiny/yolov4.cfg"
YOLO_V3_TINY_RESOLUTION = 448

YOLO_V3_WEIGHTS = "./YOLO v4/320/yolov4.weights"
YOLO_V3_CONFIGS = "./YOLO v4/320/yolov4.cfg"
YOLO_V3_RESOLUTION = 320

YOLO_V4_TINY_WEIGHTS = "./YOLO v4/tiny/yolov4.weights"
YOLO_V4_TINY_CONFIGS = "./YOLO v4/tiny/yolov4.cfg"
YOLO_V4_TINY_RESOLUTION = 416

YOLO_V4_WEIGHTS = "./YOLO v4/320/yolov4.weights"
YOLO_V4_CONFIGS = "./YOLO v4/320/yolov4.cfg"
YOLO_V4_RESOLUTION = 320
