FROM python:3.11.4-slim

WORKDIR /camerai

COPY requirements.txt .

RUN apt-get update
RUN apt-get -y install cron ffmpeg libsm6 libxext6

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install -r requirements.txt

COPY . .

RUN python -m grpc_tools.protoc -I ./libs/CamerAIProtos/ --python_out=./src/ --grpc_python_out=./src/ ./libs/CamerAIProtos/Node.proto

CMD ["python", "-m", "src.node"]
