services:
    camerapi:
        build:
            context: ./CamerAPI
            dockerfile: Dockerfile
        container_name: camerapi
        restart: unless-stopped
        env_file: ./CamerAPI/.env
        ports:
            - "8080:8080"
        volumes:
            - "./CamerAPI/temporal_videos:/camerapi/temporal_videos"
            - "./CamerAPI/.env:/camerapi/.env"
    camerai:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: camerai
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - PYTHONPATH=/camerai/src
        ports:
            - "50051:50051"
        volumes:
            - "./Images:/camerai/Images"
            - "./camerai.log:/camerai/camerai.log"
            - "./.env:/camerai/.env"
    videos_processor:
        build:
            context: ./videos_processor
            dockerfile: Dockerfile
        container_name: camerai_videos_processor
        restart: unless-stopped
        env_file:
            - ./videos_processor/.env
    camerapp:
        build:
            context: ./CamerAPP/camerapp
            dockerfile: Dockerfile
        container_name: camerapp
        restart: unless-stopped
        env_file:
            - ./CamerAPP/camerapp/.env
        ports:
            - "3000:3000"
        volumes:
            - "./CamerAPP/camerapp/.env:/camerapp/.env"