version: "2.1"
services:
  camerapi:
    build:
      context: ./CamerAPI
      dockerfile: Dockerfile
    container_name: camerapi
    restart: unless-stopped
    env_file: ./CamerAPI/.env
    ports:
      - "8080:8080"
    volumes:
      - "./CamerAPI/temporal_videos:/app/temporal_videos"
      - "./CamerAPI/.env:/app/.env"
  camerai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camerai
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "5460:5460"
    volumes:
      - "./Images:/app/Images"
      - "./camerai.log:/app/camerai.log"
      - "./.env:/app/.env"
  camerapp:
    build:
      context: ./CamerAPP/camerapp
      dockerfile: Dockerfile
    container_name: camerapp
    restart: unless-stopped
    env_file:
      - ./CamerAPP/camerapp/.env
    ports:
      - "3000:4173"
    volumes:
      - "./CamerAPP/camerapp/.env:/app/.env"