version: "2.1"
services:
  camerapi:
    build:
      context: ./CamerAPI
      dockerfile: Dockerfile
    image: node:latest
    container_name: camerapi
    restart: unless-stopped
    env_file: ./CamerAPI/.env
    ports:
      - "8080:8080"
    volumes:
      - "./CamerAPI/camerai.db:/app/camerai.db"
      - "./CamerAPI/temporal_videos:/app/temporal_videos"
  camerai:
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.10.12
    container_name: camerai
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "5460:5460"
    volumes:
      - "./Images:/app/Images"
      - "./camerai.log:/app/camerai.log"