FROM python:3.11.4-slim

WORKDIR /camerai
COPY . .

RUN apt-get update
RUN apt-get -y install cron ffmpeg libsm6 libxext6

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install -r requirements.txt --no-cache-dir

CMD ["python", "-m", "src.node"]
